from datetime import datetime

from pydantic import BaseModel, Field


class QAReport(BaseModel):
    """
    Result generated by the QA Agent after reviewing a developer report.
    """

    task_id: int = Field(..., description="Unique task identifier")

    quality_score: float = Field(
        ...,
        ge=0,
        le=100,
        description="Overall quality score"
    )

    bugs_found: int = Field(
        default=0,
        ge=0,
        description="Number of bugs/issues detected"
    )

    passed: bool = Field(
        default=False,
        description="Whether the task passed QA"
    )

    comments: str = Field(
        default="",
        description="QA feedback"
    )

    timestamp: datetime = Field(
        default_factory=datetime.utcnow
    )

    def summary(self) -> str:
        status = "PASSED" if self.passed else "FAILED"

        return (
            f"[QA] Task {self.task_id} | "
            f"{status} | "
            f"Score={self.quality_score:.1f} | "
            f"Bugs={self.bugs_found}"
        )

    def to_dict(self):
        return self.model_dump()